# Site settings
title: Last to triumph
email: yizhong.pku@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a personal blog. Zhong Yi uses this blog to share learning experiences 
  and keep some daily thoughts. This website is continually improved along with 
  Zhong Yi's learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thuzhongyi.github.io" # the base hostname & protocol for your site
twitter_username: YiZhongPKU
github_username:  thuzhongyi

# Build settings
markdown: kramdown
highlighter: pygments